data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 2000
  
train_model:
  model: "randomforest"
  n_estimators: 40
  max_depth: 15
  
model_eval:
  tracking_uri: "http://ec2-16-171-116-127.eu-north-1.compute.amazonaws.com:5000/"

model_register:
  tracking_uri: "http://ec2-16-171-116-127.eu-north-1.compute.amazonaws.com:5000/"

